### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ssorgatem** [mohitmv/r2py#1]
The readme says "all rights reserved".
I wonder, what implications does that have regarding the license of the generated code?

Is it even allowed to use r2py?
Is it allowed to fork it and modify it?

**Comment by mohitmv** [comment]
updated README. You can fork and modify.

**Comment by ssorgatem** [comment]
Thank you, but not explicitly claiming the copyright doesn't change anything, as it's still implicitly the same.

If you intend this to be public domain you should state it in the README, or just go with any standard license that fits what you intend (MIT, BSD, GPL, etc.)

My suggestion would be a 0-clause BSD license, which would be this:

> Permission to use, copy, modify, and/or distribute this software for any
purpose with or without fee is hereby granted.
>
> THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
>

**Comment by mohitmv** [comment]
Done.
Added  https://github.com/mohitmv/r2py/blob/master/LICENSE
